// <auto-generated />
using System;
using Administracion_Consorcio_PW3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Administracion_Consorcio_PW3.Migrations
{
    [DbContext(typeof(ConsorcioDbContext))]
    partial class ConsorcioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Consorcio", b =>
                {
                    b.Property<int>("IdConsorcio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsorcio"));

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaVencimientoExpensas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdConsorcio");

                    b.HasIndex("IdProvincia");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Consorcios");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Gasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGasto"));

                    b.Property<int>("AnioExpensa")
                        .HasColumnType("int");

                    b.Property<string>("ArchivoComprobante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGasto")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConsorcio")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoGasto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int>("MesExpensa")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGasto");

                    b.HasIndex("IdConsorcio");

                    b.HasIndex("IdTipoGasto");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.TipoGasto", b =>
                {
                    b.Property<int>("IdTipoGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoGasto"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoGasto");

                    b.ToTable("TiposGasto");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Unidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("ApellidoPropietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPropietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConsorcio")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePropietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Superficie")
                        .HasColumnType("int");

                    b.HasKey("IdUnidad");

                    b.HasIndex("IdConsorcio");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Consorcio", b =>
                {
                    b.HasOne("Administracion_Consorcio_PW3.Models.Entidades.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Administracion_Consorcio_PW3.Models.Entidades.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Gasto", b =>
                {
                    b.HasOne("Administracion_Consorcio_PW3.Models.Entidades.Consorcio", "Consorcio")
                        .WithMany("Gastos")
                        .HasForeignKey("IdConsorcio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Administracion_Consorcio_PW3.Models.Entidades.TipoGasto", "TipoGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("IdTipoGasto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Administracion_Consorcio_PW3.Models.Entidades.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consorcio");

                    b.Navigation("TipoGasto");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Unidad", b =>
                {
                    b.HasOne("Administracion_Consorcio_PW3.Models.Entidades.Consorcio", "Consorcio")
                        .WithMany("Unidades")
                        .HasForeignKey("IdConsorcio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Administracion_Consorcio_PW3.Models.Entidades.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consorcio");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.Consorcio", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Administracion_Consorcio_PW3.Models.Entidades.TipoGasto", b =>
                {
                    b.Navigation("Gastos");
                });
#pragma warning restore 612, 618
        }
    }
}
